language: php

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - hhvm

before_script:
 - composer self-update
 - composer install
 - mkdir -p build/logs

script:
 - phpunit --coverage-clover build/logs/clover.xml
 - php vendor/bin/coveralls -v

